export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGOUT = "LOGOUT";

export const CREATE_PROJECT = "CREATE_PROJECT";

export const CREATE_PROJECT_CATEGORY = "CREATE_CATEGORY";

export const CREATE_WELCOME = "CREATE_WELCOME";

export const CREATE_TUTO = "CREATE_TUTO";

export const CREATE_TUTO_CATEGORY = "CREATE_TUTO_CATEGORY";

export const CREATE_NEWS = "CREATE_NEWS";

export const GET_PROJECTS = "GET_PROJECTS";

export const TOGGLE_VISIBILITY = "TOGGLE_VISIBILITY";
